### PR TITLE
Fixed Bugs

### PR DESCRIPTION
**Pull request by TurboTanker**
There were some bugs in your original code where, if the computer does not know what an musicxml file is, than the code would never think any files are of that type. In my case, it would not accept any mxl or xml files. I modified that code along with another line that used the "contains" method on a string where it had never been defined.

### CODE REVIEW

**Comment by SzAmmi** [comment]
Thank! for the report! I'll look at this soon. I've very important exams
now.

2015-10-12 2:22 GMT+02:00 TurboTanker <notifications@github.com>:

> There were some bugs in your original code where, if the computer does not
> know what an musicxml file is, than the code would never think any files
> are of that type. In my case, it would not accept any mxl or xml files. I
> modified that code along with another line that used the "contains" method
> on a string where it had never been defined.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/SzAmmi/musicXml2scratch/pull/5
> Commit Summary
>
>    - Bug Fixes
>    - Fixed Same Accidental Changes
>    - Fixed Possible Issue
>
> File Changes
>
>    - *M* drumsConvert.js
>    <https://github.com/SzAmmi/musicXml2scratch/pull/5/files#diff-0> (2)
>    - *M* index.html
>    <https://github.com/SzAmmi/musicXml2scratch/pull/5/files#diff-1> (2)
>    - *M* progress.js
>    <https://github.com/SzAmmi/musicXml2scratch/pull/5/files#diff-2> (2)
>
> Patch Links:
>
>    - https://github.com/SzAmmi/musicXml2scratch/pull/5.patch
>    - https://github.com/SzAmmi/musicXml2scratch/pull/5.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SzAmmi/musicXml2scratch/pull/5>.
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by TurboTanker** [comment]
Sorry, when is soon? Do you still have exams?

**Comment by SzAmmi** [comment]
Nope, 'working on private projects. But thanks for remembering me for
mxml2scratch, I will check it out tomorrow.

2015-11-18 1:13 GMT+01:00 TurboTanker <notifications@github.com>:

> Sorry, when is soon? Do you still have exams?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SzAmmi/musicXml2scratch/pull/5#issuecomment-157551962>
> .
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by SzAmmi** [comment]
Hey! It's fixed now. If You saw some errors write to me. Sorry for late reply. I did my private project :)

**Pull request closed without merging**
